name = "Sakopack"
author = "sako"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "994ca324dbb9bf3478bf475afc7afa8ad2003cd585e7bba52844b2de20d563e7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.2"
