when:
  event: cron
  cron: "update flake"

steps:
  update:
    image: ghcr.io/nixos/nix:latest
    commands:
      - "nix-shell -p git --run 'git config --global user.email 'bot@sako.lol' && git config --global user.name 'sako-ci' && git checkout -b flake-lock-update && nix --experimental-features \"flakes nix-command\" flake update && git commit -m \"flake.lock: update\" -a'"
  push:
    image: johnwalkerx/gitea-pull-request-create-plugin:latest
    #pull: true
    settings:
      gitea_address: https://git.sako.lol
      gitea_token:
        from_secret: token
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      branch: flake-lock-update 
      base_branch: master 
      pr_title: "flake.lock: update"
      pr_body: update flake.lock 
      skip_on_missing_branch: false 
      close_pr_if_empty: true
      delete_branch_if_pr_empty: true
      merge_when_checks_succeed: false 
      delete_branch_after_merge: true
