when:
  event: cron
  cron: "update flake"

steps:
  update:
    image: ghcr.io/nixos/nix:latest
    commands:
      - nix flake update
  push:
    image: appleboy/drone-git-push
    settings:
      branch: flake-lock-update 
      local_ref: flake-lock-update
      ssh_key:
        from_secret: ssh_key
      remote: ssh://forgejo@git.sako.lol/sako/nixos.git
      force: false
      commit: true
      commit_message: "flake.lock: update"
      author_name: "sako-ci"
      author_email: "bot@sako.lol"
  pr:
    image: johnwalkerx/gitea-pull-request-create-plugin:latest
    pull: true
    settings:
      gitea_address: https://git.sako.lol
      gitea_token:
        from_secret: token
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      branch: flake-lock-update 
      base_branch: master 
      pr_title: "flake.lock: update"
      pr_body: update flake.lock 
      skip_on_missing_branch: false 
      close_pr_if_empty: true
      delete_branch_if_pr_empty: true
      merge_when_checks_succeed: false 
      delete_branch_after_merge: true
